### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by samyam81**
I wanted to help in the Documentation.

### CODE REVIEW

**Comment by krkarma777** [comment]
Hi @samyam81,

Thank you for your contribution and your willingness to help with the documentation. As this repository is quite old, I will review the current state of the project and update the documentation soon.

**Comment by samyam81** [comment]
My sincerest apologies for inadvertently forking your esteemed repository. My original intention was to contribute by crafting meticulous documentation. Serendipitously, I stumbled upon your repository, realizing it to be the perfect canvas for my aspirations. Please accept my sincerest apologies for any inconvenience caused by this unforeseen disturbance.

**Comment by krkarma777** [comment]
No need to apologize! It sounds like you had good intentions, and I appreciate your thoughtful approach to contributing. If you have any questions or need assistance with documentation or anything else related to the repository, feel free to ask.

**Comment by krkarma777** [comment]
If you contribute to the README.md or any other documentation, I would greatly appreciate it.

**Comment by samyam81** [comment]
Thank you so much for allocating time in this. Nothing but, wish you absolute best.

**Comment by samyam81** [comment]
I am currently learning Java and its Vast ecosystem. It will be pleasure writing documentation.

**Pull request merged**
